server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456




